### ISSUE TITLE
Normal address vs. lat;lon;radius

### ISSUE THREAD

**Issue by wzjoriv** [JosueCom/LAR-frontend#18]
- [x] When the user submit a request, use RegExp to detect normal address vs lat;lon;radius and execute the appropriate backend call based on that
- [x] Use UseEffect to listen for changes to location and update search text to display lat;lon;radius

**Comment by wzjoriv** [comment]
Potential regular expression:
* /^\s*-?\d+(\.\d+)?\s*;\s*-?\d+(\.\d+)?\s*;\s*\d+(\.\d+)?\s*$/

**Comment by PruthviSamirPatel** [comment]
It seems like the isProgrammaticMove value is only true at the start of when the page reloads, and is false for all the following renders. I console.logged the value for isProgrammaticMove.current, and when I search a city with the search bar, the value outputted is false when it should be true. 

The value is correctly false when I drag along the map to change locations, but its value is not true when a location change occurs through search.

**Comment by PruthviSamirPatel** [comment]
The location.radius value does not change despite changing the zoom level of the map. It seems to be stuck at 1500.

**Comment by wzjoriv** [comment]
We can discuss it during today's meeting. I am not sure why it may not be working for you

Also, the radius calculation is not working in the current main branch but will work after I make a pull request for #15. We can just focus on the UI working for now

**Comment by wzjoriv** [comment]
I don't see any changes to the branch for this issue. Have you committed/pushed the changes made so far?

**Comment by PruthviSamirPatel** [comment]
Yes, I have pulled the latest changes. I have committed the changes but not pushed them. Will do right now

**Comment by wzjoriv** [comment]
I had the code change isProgramaticMove when the map is moved, not when location is updated so that is why it didn't work. There may be a few options to fix it:

1. Make isProgramaticMove a state and listen for it (may cause some issues with useEffect double rendering if location is included as a dependency). If you want to give it a try, you can make it an state within this issue's branch, listen for it and don't include location as a dependency. useCallbacks can be used to remove the need to include location as a dependency. Look at how I used useCallbacks on branch [@JosueCom/LAR-frontend/15](https://github.com/JosueCom/LAR-frontend/tree/15-map-viewer-component-heatmap-render) for issue #15 as an example.
2. Check if isProgramaticMove can be update before location is changed (i.e. not necessarily when the map is actually moved)

I will look into these options but for now, feel free to work onto the other features. You can give it an try at one of the oprions if you like to. Also, re-include the other things in the dependencies for useEffect and remove the warning comment. I forgot only states cause UseEffect to trigger

**Comment by wzjoriv** [comment]
@PruthviSamirPatel I merged to main my changes for better radius detection for issue #15 in #20  and rebased them to the branch for this task. I also resolved the things discussed before. Feel free to close this issue if you agree after taking a look. You can get started on the other tasks

**Comment by wzjoriv** [comment]
Before you close it it, I suggest reducing the decimal places displayed in search bar. Potentially based on zoom level. The radius can be converted to a whole number

**Comment by PruthviSamirPatel** [comment]
Sounds good, will do.
