### ISSUE TITLE
Heatmap toggle button

### ISSUE THREAD

**Issue by wzjoriv** [JosueCom/LAR-frontend#23]

**Comment by PruthviSamirPatel** [comment]
ignore comment

**Comment by wzjoriv** [comment]
@PruthviSamirPatel I think the branch is ready for a pull request. Check it out and let me know

**Comment by PruthviSamirPatel** [comment]
Ok 👍. I am just adding some styling (for positioning) and then will make the pull request

**Comment by wzjoriv** [comment]
Closed with Pull Request #28
